### ISSUE TITLE
Float value fields

### ISSUE THREAD

**Issue by nsavic89** [kyouko-taiga/trexmo#1]
These fields show a delay while one is trying to enter a value in. Sometimes the entered value appears but the tool even deletes it very quickly.

**Comment by kyouko-taiga** [comment]
This happens because the state of the form has to be in sync with the server so that preconditions can be computed correctly. An update of the state is triggered every time you type a character in the input field. So if you happen to have some lag with your connection to the server, you might type faster than the server can update its state.

One solution could be to add a delay on custom input fields that would trigger the server update every n milliseconds instead of every key event. But that might make the application look less responsive.

I'll make some tests to see how it goes.
