### ISSUE TITLE
A bug with DDTL files updating

### ISSUE THREAD

**Issue by nsavic89** [kyouko-taiga/trexmo#2]
After I start the tool running on my Linux machine with defined package of the DDTL files it seems that the current version of these files stays memorized somewhere. I have this belief since when I update some of the files (e.g. add a new field), save the changes and re-open the internet browser (or re-start trexmo in the terminal) the changes are not applied (e.g. a new defined field does not appear in the list for the corresponding model). The new field would only appear in the list, if: 1. the Linux was restarted or 2. name of the modified file was renamed.
This was not a case with the first (alpha) version...where it was possible to modify the DDTL and do the testing in parallel.

**Comment by kyouko-taiga** [comment]
This is due to the application cache. When DDTL files are parsed for the first time, they are put in a cache for a while so that TREXMO doesn't need to parse them again.

You can either disable the application cache for DDTL files (which will greatly affect the performances) by setting in the settings (`trexmo/settings.py`):

``` python
USE_CACHE_FOR_DDTL = False
```

Or you can manually reset the entire cache every time you make an update:

```
python manage.py clear
```

Note that the second method will also make everything a bit slower the first time you reload your application, as the DDTL will have to be parsed again, but only once.
